config/routes.rb
Rails.application.routes.draw do
  resources :resumes, :only => [:edit, :new, :create, :index, :show, :update]

  resources :users, :only => [:edit, :new, :create, :index, :show, :update]
  
  resources :interests, :only => [:edit, :new, :create, :index, :show, :update]
  
  resources :languages, :only => [:edit, :new, :create, :index, :show, :update]

  resources :skilltypes, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :skills, :only => [:edit, :new, :create, :update]
  end

  resources :employments, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :positions, :only => [:edit, :new, :create, :index, :show, :update] do
      resources :responsibilities, :only => [:edit, :new, :create, :index, :show, :update]
    end
  end

  resources :positions, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :responsibilities, :only => [:edit, :new, :create, :index, :show, :update]
  end

  resources :educations, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :degrees, :only => [:edit, :new, :create, :update]
    resources :achievements, :only => [:edit, :new, :create, :update]
  end

  get '/', to: 'users#index'
  get '/login', to: 'users#index'
  post '/login', to: 'users#login'
  get '/logout', to: 'users#logout'
  get '/register', to: 'users#new'
  get '/profile', to: 'users#profile'
  get '/profile/edit', to: 'users#profileEdit'
  

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :education
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  belongs_to :education
end

app/models/education.rb
class Education < ActiveRecord::Base
  
  belongs_to :user
  has_many :degrees
  has_many :achievements

  # attr_accessor :educationDegrees

  # def initialize(attributes = {})
  #   @educationDegrees = attributes[:educationDegrees]
  # end 

end

app/models/employment.rb
class Employment < ActiveRecord::Base

  belongs_to :user
  has_many :positions

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
end

app/models/language.rb
class Language < ActiveRecord::Base
  belongs_to :user
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :employment
  has_many :responsibilities
end

app/models/responsibility.rb
class Responsibility < ActiveRecord::Base
  belongs_to :position
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :skilltype
end

app/models/skilltype.rb
class Skilltype < ActiveRecord::Base
  belongs_to :user
  has_many :skills
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	
	has_many :educations
	has_many :employments
	has_many :skilltypes
	has_many :languages
	has_many :interests

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  # GET /positions/1
  # GET /positions/1.json
  def show 
    @responsibility = Responsibility.new
    @responsibilities = Responsibility.where(position_id: @position.id)
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
    @employment = Employment.find(params[:employment_id])
  end

  # POST /positions
  # POST /positions.json
  def create
    
    @employment = Employment.find(params[:employment_id])
    @position = @employment.positions.build(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @employment, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    @employment = Employment.find(params[:employment_id])
    
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:title, :startDate, :endDate, :employment_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/skilltypes_helper.rb
module SkilltypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/positions/_form.html.erb
<%= form_for [@employment, @position] do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :startDate %><br>
    <%= f.date_select :startDate %>
  </div>
  <div class="field">
    <%= f.label :endDate %><br>
    <%= f.date_select :endDate %>
  </div>
  
  <%= f.hidden_field :employment_id, :value => @employment.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<div class='center'>
	<div class='formContainer'>
		<div class='listTitle'>
			<p>EDIT POSITIONS</p>
		</div>
		<%= render 'form' %>
	</div>
</div>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Positions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Employment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.title %></td>
        <td><%= position.startDate %></td>
        <td><%= position.endDate %></td>
        <td><%= position.employment %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<div class='center'>
	<div class='listContainer'>
		<div class='listTitle'>
			<p>NEW POSITION</p>
		</div>
	</div>
</div>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<div class='center'>
  	<div class='formContainer'>
    	<!-- <p id="notice">< %= notice % ></p> -->
		<div class='listTitle'>
			<p><%= @position.title %><%= link_to 'Edit', edit_position_path(@position), class: "button workhistory" %></p>
		</div>
		<div class='lists'>
			<div class='info'>
				<p>
				  <strong>Title:</strong>
				  <%= @position.title %>
				</p>

				<p>
				  <strong>Startdate:</strong>
				  <%= @position.startDate %>
				</p>

				<p>
				  <strong>Enddate:</strong>
				  <%= @position.endDate %>
				</p>

				<h2>Responsibilities</h2>
				<% @responsibilities.each do |responsibility| %>
					<h3><%= responsibility.description %></h3>
				<% end %>

<%= render 'responsibilities/form' %>
	    </div>
	  </div>
	</div>
</div> 