config/routes.rb
Rails.application.routes.draw do
  resources :resumes, :only => [:edit, :new, :create, :index, :show, :update]

  resources :users, :only => [:edit, :new, :create, :index, :show, :update]
  
  resources :interests, :only => [:edit, :new, :create, :index, :show, :update]
  
  resources :languages, :only => [:edit, :new, :create, :index, :show, :update]

  resources :skilltypes, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :skills, :only => [:edit, :new, :create, :update]
  end

  resources :employments, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :positions, :only => [:edit, :new, :create, :index, :show, :update] do
      resources :responsibilities, :only => [:edit, :new, :create, :index, :show, :update]
    end
  end

  resources :positions, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :responsibilities, :only => [:edit, :new, :create, :index, :show, :update]
  end

  resources :educations, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :degrees, :only => [:edit, :new, :create, :update]
    resources :achievements, :only => [:edit, :new, :create, :update]
  end

  get '/', to: 'users#index'
  get '/login', to: 'users#index'
  post '/login', to: 'users#login'
  get '/logout', to: 'users#logout'
  get '/register', to: 'users#new'
  get '/profile', to: 'users#profile'
  get '/profile/edit', to: 'users#profileEdit'
  

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :education
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  belongs_to :education
end

app/models/education.rb
class Education < ActiveRecord::Base
  
  belongs_to :user
  has_many :degrees
  has_many :achievements

  # attr_accessor :educationDegrees

  # def initialize(attributes = {})
  #   @educationDegrees = attributes[:educationDegrees]
  # end 

end

app/models/employment.rb
class Employment < ActiveRecord::Base

  belongs_to :user
  has_many :positions

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
end

app/models/language.rb
class Language < ActiveRecord::Base
  belongs_to :user
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :employment
  has_many :responsibilities
end

app/models/responsibility.rb
class Responsibility < ActiveRecord::Base
  belongs_to :position
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :skilltype
end

app/models/skilltype.rb
class Skilltype < ActiveRecord::Base
  belongs_to :user
  has_many :skills
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	
	has_many :educations
	has_many :employments
	has_many :skilltypes
	has_many :languages
	has_many :interests

end

app/controllers/responsibilities_controller.rb
class ResponsibilitiesController < ApplicationController
  before_action :set_responsibility, only: [:show, :edit, :update, :destroy]

  # GET /responsibilities
  # GET /responsibilities.json
  def index
    @responsibilities = Responsibility.where(user_id: current_user.id, position_id: @position.id)
  end

  # GET /responsibilities/1
  # GET /responsibilities/1.json
  def show
  end

  # GET /responsibilities/new
  def new
    @responsibility = Responsibility.new
  end

  # GET /responsibilities/1/edit
  def edit
  end

  # POST /responsibilities
  # POST /responsibilities.json
  def create

    # http://stackoverflow.com/questions/22446647/undefined-method-model-url
    @position = Position.find(params[:position_id])
    @responsibility = @position.responsibilities.build(responsibility_params)

    respond_to do |format|
      if @responsibility.save
        format.html { redirect_to @position, notice: 'Responsibility was successfully created.' }
        format.json { render :show, status: :created, location: @responsibility }
      else
        format.html { render :new }
        format.json { render json: @responsibility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responsibilities/1
  # PATCH/PUT /responsibilities/1.json
  def update
    respond_to do |format|
      if @responsibility.update(responsibility_params)
        format.html { redirect_to @responsibility, notice: 'Responsibility was successfully updated.' }
        format.json { render :show, status: :ok, location: @responsibility }
      else
        format.html { render :edit }
        format.json { render json: @responsibility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsibilities/1
  # DELETE /responsibilities/1.json
  def destroy
    @responsibility.destroy
    respond_to do |format|
      format.html { redirect_to responsibilities_url, notice: 'Responsibility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_responsibility
      @responsibility = Responsibility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def responsibility_params
      params.require(:responsibility).permit(:description, :position_id)
    end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/responsibilities_helper.rb
module ResponsibilitiesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/skilltypes_helper.rb
module SkilltypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/responsibilities/_form.html.erb
<!-- http://stackoverflow.com/questions/2034700/form-for-with-nested-resources -->
<%= form_for [@position, @responsibility] do |f| %>
  <% if @responsibility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@responsibility.errors.count, "error") %> prohibited this responsibility from being saved:</h2>

      <ul>
      <% @responsibility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Add Responsibility</h2>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <%= f.hidden_field :position_id,  :value => @position.id %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responsibilities/edit.html.erb
<div class='center'>
	<div class='formContainer'>
		<div class='listTitle'>
			<p>EDIT RESPONSIBILITIES</p>
		</div>
		<%= render 'form' %>
	</div>
</div>

app/views/responsibilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Responsibilities</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responsibilities.each do |responsibility| %>
      <tr>
        <td><%= responsibility.description %></td>
        <td><%= responsibility.position %></td>
        <td><%= link_to 'Show', responsibility %></td>
        <td><%= link_to 'Edit', edit_responsibility_path(responsibility) %></td>
        <td><%= link_to 'Destroy', responsibility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Responsibility', new_responsibility_path %>

app/views/responsibilities/new.html.erb
<div class='center'>
	<div class='listContainer'>
		<div class='listTitle'>
			<p>NEW RESPONSIBILITY</p>
		</div>
	</div>
</div>
<%= render 'form' %>

<%= link_to 'Back', responsibilities_path %>

app/views/responsibilities/show.html.erb
<div class='center'>
  	<div class='formContainer'>
    	<!-- <p id="notice">< %= notice % ></p> -->
		<div class='listTitle'>
			<p><%= @responsibility.name %><%= link_to 'Edit', edit_responsibility_path(@responsibility), class: "button workhistory" %></p>
		</div>
		<div class='lists'>
			<div class='info'>
				<p>
				  <strong>Description:</strong>
				  <%= @responsibility.description %>
				</p>

				<p>
				  <strong>Position:</strong>
				  <%= @responsibility.position %>
				</p>
			</div>
		</div>
	</div>
</div>