config/routes.rb
Rails.application.routes.draw do
  resources :resumes, :only => [:edit, :new, :create, :index, :show, :update]

  resources :users, :only => [:edit, :new, :create, :index, :show, :update]
  
  resources :interests, :only => [:edit, :new, :create, :index, :show, :update]
  
  resources :languages, :only => [:edit, :new, :create, :index, :show, :update]

  resources :skilltypes, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :skills, :only => [:edit, :new, :create, :update]
  end

  resources :employments, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :positions, :only => [:edit, :new, :create, :index, :show, :update] do
      resources :responsibilities, :only => [:edit, :new, :create, :index, :show, :update]
    end
  end

  resources :positions, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :responsibilities, :only => [:edit, :new, :create, :index, :show, :update]
  end

  resources :educations, :only => [:edit, :new, :create, :index, :show, :update] do
    resources :degrees, :only => [:edit, :new, :create, :update]
    resources :achievements, :only => [:edit, :new, :create, :update]
  end

  get '/', to: 'users#index'
  get '/login', to: 'users#index'
  post '/login', to: 'users#login'
  get '/logout', to: 'users#logout'
  get '/register', to: 'users#new'
  get '/profile', to: 'users#profile'
  get '/profile/edit', to: 'users#profileEdit'
  

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :education
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  belongs_to :education
end

app/models/education.rb
class Education < ActiveRecord::Base
  
  belongs_to :user
  has_many :degrees
  has_many :achievements

  # attr_accessor :educationDegrees

  # def initialize(attributes = {})
  #   @educationDegrees = attributes[:educationDegrees]
  # end 

end

app/models/employment.rb
class Employment < ActiveRecord::Base

  belongs_to :user
  has_many :positions

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
end

app/models/language.rb
class Language < ActiveRecord::Base
  belongs_to :user
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :employment
  has_many :responsibilities
end

app/models/responsibility.rb
class Responsibility < ActiveRecord::Base
  belongs_to :position
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :skilltype
end

app/models/skilltype.rb
class Skilltype < ActiveRecord::Base
  belongs_to :user
  has_many :skills
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	
	has_many :educations
	has_many :employments
	has_many :skilltypes
	has_many :languages
	has_many :interests

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.where(user_id: current_user.id)
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show

    require 'json'

    # @resume[:userName] = "testing"

    @resumeHash = {}

    @resumeHash[:userName] = current_user.fname + " " + current_user.lname
    @resumeHash[:name] = @resume[:name]

    interests = @resume[:interests]
    interests = JSON.parse interests
    interests = Interest.where(id: interests).as_json#.to_json#.delete!('\\')



    # puts("---raw----")
    # puts(interests)
    # puts("---raw----")
    # puts("---to_json----")
    # puts(interests.to_json)
    # puts("---to_json----")
    # puts("---JSON parse----")
    # puts(JSON.parse interests)
    # puts("---JSON parse----")
    @resumeHash[:interests] = interests.to_json

    skills = @resume[:skills]
    skills = JSON.parse skills
    skills = Skilltype.where(id: skills).as_json
    @resume[:skills] = skills

    # puts("----resume----")
    # puts(@resume.inspect)
    # puts("----resume----")

    mustache_render @resumeHash, 'resume1'
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
    @interests = Interest.where(user_id: current_user.id)
    @languages = Language.where(user_id: current_user.id)

    @educations = Education.where(user_id: current_user.id)
    @educations.each do | education |
      education.degrees = Degree.where(education_id: education.id)
    end 

    @employments = Employment.where(user_id: current_user.id)
    @employments.each do | employment |
      employment.positions = Position.where(employment_id: employment.id)
      employment.positions.each do | position |
        position.responsibilities = Responsibility.where(position_id: position.id)
      end
    end

    @skilltypes = Skilltype.where(user_id: current_user.id)
    @skilltypes.each do | skilltype |
      skilltype.skills = Skill.where(skilltype_id: skilltype.id )
    end
    
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    require 'json'
    puts(params)

    # skills
    # http://stackoverflow.com/questions/6210572/how-to-replace-a-hash-key-with-another-key
    # hash[:new_key] = hash.delete :old_key

    params['resume'][:skills] = params['resume'][:skilltype].to_json
    params['resume'].delete :skilltype

    params['resume'][:interests] = params['resume'][:interest].to_json
    params['resume'].delete :interest

    params['resume'][:languages] = params['resume'][:language].to_json
    params['resume'].delete :language

    params['resume'][:employment] = params['resume'][:employment].to_json

    params['resume'][:education] = params['resume'][:education].to_json

    @params = params['resume']



    @resume = Resume.new(resume_params)  

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # mustache render
    # http://stackoverflow.com/questions/15754177/whats-the-simplest-way-to-use-mustache-view-templates-in-rails
    def mustache_render(hash, template)
        vw = File.read('./app/views/mustache/' + template + '.html.mustache') || ""
        puts("------------")
        puts( Mustache.render(vw, hash) )
        puts("------------")
        render :text => Mustache.to_html(vw, hash), :layout => true
    end


    def array_to_int array
      array.map(&:to_i)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:name, :skills, :languages, :interests, :user_id, :employment, :education, :user_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/skilltypes_helper.rb
module SkilltypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/resumes/_form.html.erb
<!-- http://surrealdetective.github.io/blog/2013/07/01/the-nested-ruby-params-hash-for-complex-html-forms-and-sinatra/ -->
<div class="form-wrapper">
  
  <%= form_for(@resume) do |f| %>
    <% if @resume.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

        <ul>
        <% @resume.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name, "Resume Name" %><br>
      <%= f.text_field :name %>
    </div>
    
    <%= f.hidden_field :user_id, :value => current_user.id%>
    <div class='listTitle'>
      <p>education</p>
    </div>
    <div>
      <% @educations.each_with_index do | education, index | %>
        <div class="listItem">
          <h2>
            <!-- <%=check_box("education", index)%> -->
            <%= check_box_tag "resume[education][]", education.id %>
            <%= education.name %>
          </h2>
        </div>
        

        <% education.degrees.each_with_index do | degree, degreeIndex | %>
          <div class="listItem">
          
            <!-- <h3><%=check_box("education", "degree", {:multiple => true}, degreeIndex )%><%= degree.level %></h3> -->
            <h3>
              <%= check_box_tag "resume[education][][degree][]", degree.id %>
              <%= degree.level %>
            </h3>
          </div>
          
        <% end %>
      <% end %>
    </div>
    
    <div class='listTitle'>
      <p>employment</p>
    </div>
    <div>
      <% @employments.each_with_index do | employment, index | %>
        <div class="listItem">
          <h2>
            <!-- <%=check_box("resume", "employment", {:multiple => true}, index)%> -->
            <%= check_box_tag "resume[employment][]", employment.id %>
            <%= employment.name %>
          </h2>  
        </div>
        <% employment.positions.each_with_index do | position, positionIndex | %>
          <div class="listItem">
            <h3>
              <!-- <%=check_box("employment", "position", {:multiple => true}, index, nil )%> -->
              <%= check_box_tag "resume[employment][][position][]", position.id %>
              <%= position.title %>
            </h3>
          </div>
          <div class="list">
            <% position.responsibilities.each_with_index do | responsibility, responsiblityIndex | %>
              <div class="listItem">
                <h4>
                  <%= check_box_tag "resume[employment][][position][][responsibility][]", responsibility.id %>
                  <%= responsibility.description%>
                </h4>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class='listTitle'>
      <p>skills</p>
    </div>
    <div>
      <% @skilltypes.each_with_index do | skilltype, index | %>
        <div class="listItem">
          <h2>
            <%= check_box_tag "resume[skilltype][]", skilltype.id %>
            <%= skilltype.name %>
          </h2>
        </div>
        <% skilltype.skills.each do | skill | %>
          <div class="listItem">
            <h3>
              <%= check_box_tag "resume[skilltype][][skill][]", skill.id %>
              <%= skill.name %>
            </h3>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="listTitle">
      <p>languages</p>
    </div>  
     <div>
      <% @languages.each_with_index do | language, index | %>
        <div class="listItem">
          <h2>
            <%= check_box_tag "resume[language][]", language.id %>
            <%= language.language %>
          </h2>
        </div>
      <% end %>
    </div>
    <div class="listTitle">
      <p>interests</p>
    </div>  
     <div>
      <% @interests.each_with_index do | interest, index | %>
        <div class="listItem">
          <h2>
            <%= check_box_tag "resume[interest][]", interest.id %>
            <%= interest.name %>
          </h2>
        </div>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<div class='left'>

    <div class='listContainer'>
    
        <div class='listTitle'>
            <p>RESUMES</p>
        </div>
		<% @resumes.each do |resume| %>
		<div class='lists'>
		<a href="/resumes/<%= resume.id%>"><%= resume.name %></a>
		            <hr>
          </div>  
        <% end %>
    </div>
</div>

<div class='right'>
    <div class='resumes'><%= link_to 'NEW RESUME', new_resume_path %></div>

app/views/resumes/new.html.erb
<div class='center'>
  <div class='formContainer'>
  	<div class="listTitle">
  		<p>new resume</p>
  	</div>
  	<div class="lists">
		<%= render 'form' %>  		
  	</div>
  </div>
</div>

app/views/resumes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @resume.name %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @resume.skills %>
</p>

<p>
  <strong>Languages:</strong>
  <%= @resume.languages %>
</p>

<p>
  <strong>Interests:</strong>
  <%= @resume.interests %>
</p>

<p>
  <strong>User:</strong>
  <%= @resume.user %>
</p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>